### ISSUE TITLE
Component header error

### ISSUE THREAD

**Issue by jasa** [Bareflank/pal#102]
This code seems no to work properly. It generates not a header for each component but it generates the same header (last component from previous "for loop") and overwrites it.
 
https://github.com/Bareflank/pal/blob/f47fa19bdad8898b42479d41ac18f5d88f028d07/pal/generator/cxx_header_generator.py#L49-L54

I have made a quick fix according to my understanding, is it correct or are i'm wrong?.
``` python
            for name, regs in peripherals.items():
                include_guard = "PAL_" + regs[0].component.upper() + "_H"
                self.gadgets["pal.include_guard"].name = include_guard
                self.gadgets["pal.cxx.namespace"].name = "pal::" + regs[0].component.lower() # namespace_name
                outfile_path = os.path.join(outpath, regs[0].component.lower() + ".h")
                outfile_path = os.path.abspath(outfile_path)
```

**Comment by JaredWright** [comment]
You're right @jasa, nice find! I think the code above _does_ generate the right output in some cases, but it only works by chance because of the way that `generate_registers()` is being called for components/peripheral devices. For example, the following runner groups together registers that belong to a single ACPI table (a "component" in this case), generating each separately: https://github.com/Bareflank/pal/blob/f47fa19bdad8898b42479d41ac18f5d88f028d07/pal/runner/acpi_runner.py#L25-L30)

In either case, you've identified a very fragile piece of code. Would you like to contribute a pull request with your changes? Or would you prefer that I open one?

**Comment by jasa** [comment]
I also just realized that the generated header files also uses deprecated c headers.
```C++
#ifndef PAL_PWR_H
#define PAL_PWR_H

#include <stdint.h>

namespace pal::pwr
{
    struct view { uintptr_t base_address; };
    
}
#endif
```

**Comment by JaredWright** [comment]
Yep, the C++11 generator does generate a dependency on stdint.h by default (probably not ideal in all cases). However, the header used here is configurable, because the project doesn't want to assume you have any standard libraries available. If you're using cmake as a build interface, you could configure the project like so:

```
cmake </path/to/pal/> -DPAL_STDINT_HEADER=my_stdint_header.h
```

Which would produce:

```
#ifndef PAL_PWR_H
#define PAL_PWR_H

#include <my_stdint_header.h>

namespace pal::pwr
{
    struct view { uintptr_t base_address; };
    
}
#endif
```

With that said, what's the best default for the C++11 generator? I see the following requirements to be considered for choosing a default, aiming for "most coverage possible" (not necessarily all)
* Works when building on Linux and Windows (using their respective compilers)
* Works for userspace applications, kernel code, and baremetal code (e.g. statically linked, free standing binary with no standard library). Probably not possible to hit all cases here with one default.
* Architecture agnostic (Intel, AMD, ARMv8, etc)
* Would additional work required in other parts of the code generator justify the new choice

If a different default header is desirable (e.g. `<cstdint>`), I think it could be changed here: https://github.com/Bareflank/pal/blob/2a5b0b3ed4698a077d9c707a1e6c692eebfb362a/pal/writer/register/cxx11/register_dependency.py#L10

**Comment by JaredWright** [comment]
By the way, thanks for the PR for the first issue you found! 👍
